server:
  port: 4488
  address: 127.0.0.1
spring:
  main:
    banner-mode: log
lavalink:
  server:
    password: "YOUR PASSWORD HERE"
    sources:
      youtube: true
      bandcamp: false
      soundcloud: false
      twitch: false
      vimeo: false
      mixer: false
      http: true
      local: false
    #ratelimit:
      #ipBlocks: ["YOUR IP BLOCK HERE"]
      #strategy: "LoadBalance"
      #searchTriggersFail: true
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 3
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
